version: '3.8'

services:
  web:
    image: saputradev/testing-push-pull-agile_web:1.0.0
    container_name: apache_ttl_sh
    restart: always
    ports:
      - "8080:8888"
    depends_on:
      - mariadb-db
    volumes:
      - ./src:/var/www/html

  mariadb-db:
    image: saputradev/testing-push-pull-agile_mariadb-db:1.0.0
    container_name: mariadb_ttl_sh
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: sample_db
      MARIADB_USER: user
      MARIADB_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: saputradev/testing-push-pull-agile_phpmyadmin:1.0.0
    container_name: phpmyadmin_ttl_sh
    depends_on:
      - mariadb-db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb-db
      UPLOAD_LIMIT: 2000M

volumes:
  db_data:
